name: Cypress Tests ğŸ§ª

on: [push]

jobs:
  Component tests ğŸ§ª:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code ğŸ›
        uses: actions/checkout@v2

      - name: Run Component tests ğŸ§ª
        uses: cypress-io/github-action@v4
        with:
          working-directory: .
          component: true

  E2E tests ğŸ§ª:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code ğŸ›
        uses: actions/checkout@v2

      - name: Run E2E tests ğŸ§ª
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm start
